// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SystemDataSpatialDbGeographyWellKnownValue system data spatial db geography well known value
//
// swagger:model System.Data.Spatial.DbGeographyWellKnownValue
type SystemDataSpatialDbGeographyWellKnownValue struct {

	// coordinate system Id
	CoordinateSystemID int32 `json:"coordinateSystemId,omitempty"`

	// well known binary
	// Format: byte
	WellKnownBinary strfmt.Base64 `json:"wellKnownBinary,omitempty"`

	// well known text
	WellKnownText string `json:"wellKnownText,omitempty"`
}

// Validate validates this system data spatial db geography well known value
func (m *SystemDataSpatialDbGeographyWellKnownValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this system data spatial db geography well known value based on context it is used
func (m *SystemDataSpatialDbGeographyWellKnownValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SystemDataSpatialDbGeographyWellKnownValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SystemDataSpatialDbGeographyWellKnownValue) UnmarshalBinary(b []byte) error {
	var res SystemDataSpatialDbGeographyWellKnownValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
