// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesJourneyPlannerFareTap tfl Api presentation entities journey planner fare tap
//
// swagger:model Tfl.Api.Presentation.Entities.JourneyPlanner.FareTap
type TflAPIPresentationEntitiesJourneyPlannerFareTap struct {

	// atco code
	AtcoCode string `json:"atcoCode,omitempty"`

	// tap details
	TapDetails *TflAPIPresentationEntitiesJourneyPlannerFareTapDetails `json:"tapDetails,omitempty"`
}

// Validate validates this tfl Api presentation entities journey planner fare tap
func (m *TflAPIPresentationEntitiesJourneyPlannerFareTap) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTapDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerFareTap) validateTapDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.TapDetails) { // not required
		return nil
	}

	if m.TapDetails != nil {
		if err := m.TapDetails.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("tapDetails")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("tapDetails")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this tfl Api presentation entities journey planner fare tap based on the context it is used
func (m *TflAPIPresentationEntitiesJourneyPlannerFareTap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTapDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerFareTap) contextValidateTapDetails(ctx context.Context, formats strfmt.Registry) error {

	if m.TapDetails != nil {

		if swag.IsZero(m.TapDetails) { // not required
			return nil
		}

		if err := m.TapDetails.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("tapDetails")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("tapDetails")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerFareTap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerFareTap) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesJourneyPlannerFareTap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
