// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TflAPIPresentationEntitiesArrivalDepartureWithLine DTO to capture the prediction details
//
// swagger:model Tfl.Api.Presentation.Entities.ArrivalDepartureWithLine
type TflAPIPresentationEntitiesArrivalDepartureWithLine struct {

	// Reason for cancellation or delay
	Cause string `json:"cause,omitempty"`

	// Status of departure
	// Enum: ["OnTime","Delayed","Cancelled","NotStoppingAtStation"]
	DepartureStatus string `json:"departureStatus,omitempty"`

	// Name of the destination
	DestinationName string `json:"destinationName,omitempty"`

	// Naptan Identifier for the prediction's destination
	DestinationNaptanID string `json:"destinationNaptanId,omitempty"`

	// Estimated time of arrival
	// Format: date-time
	EstimatedTimeOfArrival strfmt.DateTime `json:"estimatedTimeOfArrival,omitempty"`

	// Estimated time of arrival
	// Format: date-time
	EstimatedTimeOfDeparture strfmt.DateTime `json:"estimatedTimeOfDeparture,omitempty"`

	// Train operating company LineId
	LineID string `json:"lineId,omitempty"`

	// Train operating company LineName
	LineName string `json:"lineName,omitempty"`

	// Estimated time of arrival
	MinutesAndSecondsToArrival string `json:"minutesAndSecondsToArrival,omitempty"`

	// Estimated time of arrival
	MinutesAndSecondsToDeparture string `json:"minutesAndSecondsToDeparture,omitempty"`

	// Identifier for the prediction
	NaptanID string `json:"naptanId,omitempty"`

	// Platform name (for bus, this is the stop letter)
	PlatformName string `json:"platformName,omitempty"`

	// Estimated time of arrival
	// Format: date-time
	ScheduledTimeOfArrival strfmt.DateTime `json:"scheduledTimeOfArrival,omitempty"`

	// Estimated time of arrival
	// Format: date-time
	ScheduledTimeOfDeparture strfmt.DateTime `json:"scheduledTimeOfDeparture,omitempty"`

	// Station name
	StationName string `json:"stationName,omitempty"`

	// Keep the original timestamp from MongoDb fo debugging purposes
	Timing *TflAPIPresentationEntitiesPredictionTiming `json:"timing,omitempty"`

	// Train operating company VehicleId
	VehicleID string `json:"vehicleId,omitempty"`
}

// Validate validates this tfl Api presentation entities arrival departure with line
func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDepartureStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEstimatedTimeOfArrival(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEstimatedTimeOfDeparture(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScheduledTimeOfArrival(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScheduledTimeOfDeparture(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTiming(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var tflApiPresentationEntitiesArrivalDepartureWithLineTypeDepartureStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["OnTime","Delayed","Cancelled","NotStoppingAtStation"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tflApiPresentationEntitiesArrivalDepartureWithLineTypeDepartureStatusPropEnum = append(tflApiPresentationEntitiesArrivalDepartureWithLineTypeDepartureStatusPropEnum, v)
	}
}

const (

	// TflAPIPresentationEntitiesArrivalDepartureWithLineDepartureStatusOnTime captures enum value "OnTime"
	TflAPIPresentationEntitiesArrivalDepartureWithLineDepartureStatusOnTime string = "OnTime"

	// TflAPIPresentationEntitiesArrivalDepartureWithLineDepartureStatusDelayed captures enum value "Delayed"
	TflAPIPresentationEntitiesArrivalDepartureWithLineDepartureStatusDelayed string = "Delayed"

	// TflAPIPresentationEntitiesArrivalDepartureWithLineDepartureStatusCancelled captures enum value "Cancelled"
	TflAPIPresentationEntitiesArrivalDepartureWithLineDepartureStatusCancelled string = "Cancelled"

	// TflAPIPresentationEntitiesArrivalDepartureWithLineDepartureStatusNotStoppingAtStation captures enum value "NotStoppingAtStation"
	TflAPIPresentationEntitiesArrivalDepartureWithLineDepartureStatusNotStoppingAtStation string = "NotStoppingAtStation"
)

// prop value enum
func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) validateDepartureStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, tflApiPresentationEntitiesArrivalDepartureWithLineTypeDepartureStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) validateDepartureStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.DepartureStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateDepartureStatusEnum("departureStatus", "body", m.DepartureStatus); err != nil {
		return err
	}

	return nil
}

func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) validateEstimatedTimeOfArrival(formats strfmt.Registry) error {
	if swag.IsZero(m.EstimatedTimeOfArrival) { // not required
		return nil
	}

	if err := validate.FormatOf("estimatedTimeOfArrival", "body", "date-time", m.EstimatedTimeOfArrival.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) validateEstimatedTimeOfDeparture(formats strfmt.Registry) error {
	if swag.IsZero(m.EstimatedTimeOfDeparture) { // not required
		return nil
	}

	if err := validate.FormatOf("estimatedTimeOfDeparture", "body", "date-time", m.EstimatedTimeOfDeparture.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) validateScheduledTimeOfArrival(formats strfmt.Registry) error {
	if swag.IsZero(m.ScheduledTimeOfArrival) { // not required
		return nil
	}

	if err := validate.FormatOf("scheduledTimeOfArrival", "body", "date-time", m.ScheduledTimeOfArrival.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) validateScheduledTimeOfDeparture(formats strfmt.Registry) error {
	if swag.IsZero(m.ScheduledTimeOfDeparture) { // not required
		return nil
	}

	if err := validate.FormatOf("scheduledTimeOfDeparture", "body", "date-time", m.ScheduledTimeOfDeparture.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) validateTiming(formats strfmt.Registry) error {
	if swag.IsZero(m.Timing) { // not required
		return nil
	}

	if m.Timing != nil {
		if err := m.Timing.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("timing")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("timing")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this tfl Api presentation entities arrival departure with line based on the context it is used
func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTiming(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) contextValidateTiming(ctx context.Context, formats strfmt.Registry) error {

	if m.Timing != nil {

		if swag.IsZero(m.Timing) { // not required
			return nil
		}

		if err := m.Timing.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("timing")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("timing")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesArrivalDepartureWithLine) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesArrivalDepartureWithLine
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
