// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesLineRouteSection tfl Api presentation entities line route section
//
// swagger:model Tfl.Api.Presentation.Entities.LineRouteSection
type TflAPIPresentationEntitiesLineRouteSection struct {

	// destination
	Destination string `json:"destination,omitempty"`

	// direction
	Direction string `json:"direction,omitempty"`

	// from station
	FromStation string `json:"fromStation,omitempty"`

	// route Id
	RouteID int32 `json:"routeId,omitempty"`

	// service type
	ServiceType string `json:"serviceType,omitempty"`

	// to station
	ToStation string `json:"toStation,omitempty"`

	// vehicle destination text
	VehicleDestinationText string `json:"vehicleDestinationText,omitempty"`
}

// Validate validates this tfl Api presentation entities line route section
func (m *TflAPIPresentationEntitiesLineRouteSection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tfl Api presentation entities line route section based on context it is used
func (m *TflAPIPresentationEntitiesLineRouteSection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesLineRouteSection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesLineRouteSection) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesLineRouteSection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
