// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesTwentyFourHourClockTime tfl Api presentation entities twenty four hour clock time
//
// swagger:model Tfl.Api.Presentation.Entities.TwentyFourHourClockTime
type TflAPIPresentationEntitiesTwentyFourHourClockTime struct {

	// hour
	Hour string `json:"hour,omitempty"`

	// minute
	Minute string `json:"minute,omitempty"`
}

// Validate validates this tfl Api presentation entities twenty four hour clock time
func (m *TflAPIPresentationEntitiesTwentyFourHourClockTime) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tfl Api presentation entities twenty four hour clock time based on context it is used
func (m *TflAPIPresentationEntitiesTwentyFourHourClockTime) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesTwentyFourHourClockTime) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesTwentyFourHourClockTime) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesTwentyFourHourClockTime
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
