// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TflAPIPresentationEntitiesRoadDisruptionLine tfl Api presentation entities road disruption line
//
// swagger:model Tfl.Api.Presentation.Entities.RoadDisruptionLine
type TflAPIPresentationEntitiesRoadDisruptionLine struct {

	// end date
	// Format: date-time
	EndDate strfmt.DateTime `json:"endDate,omitempty"`

	// end time
	EndTime string `json:"endTime,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// is diversion
	IsDiversion bool `json:"isDiversion,omitempty"`

	// multi line string
	MultiLineString *SystemDataSpatialDbGeography `json:"multiLineString,omitempty"`

	// road disruption Id
	RoadDisruptionID string `json:"roadDisruptionId,omitempty"`

	// start date
	// Format: date-time
	StartDate strfmt.DateTime `json:"startDate,omitempty"`

	// start time
	StartTime string `json:"startTime,omitempty"`
}

// Validate validates this tfl Api presentation entities road disruption line
func (m *TflAPIPresentationEntitiesRoadDisruptionLine) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMultiLineString(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesRoadDisruptionLine) validateEndDate(formats strfmt.Registry) error {
	if swag.IsZero(m.EndDate) { // not required
		return nil
	}

	if err := validate.FormatOf("endDate", "body", "date-time", m.EndDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TflAPIPresentationEntitiesRoadDisruptionLine) validateMultiLineString(formats strfmt.Registry) error {
	if swag.IsZero(m.MultiLineString) { // not required
		return nil
	}

	if m.MultiLineString != nil {
		if err := m.MultiLineString.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("multiLineString")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("multiLineString")
			}

			return err
		}
	}

	return nil
}

func (m *TflAPIPresentationEntitiesRoadDisruptionLine) validateStartDate(formats strfmt.Registry) error {
	if swag.IsZero(m.StartDate) { // not required
		return nil
	}

	if err := validate.FormatOf("startDate", "body", "date-time", m.StartDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this tfl Api presentation entities road disruption line based on the context it is used
func (m *TflAPIPresentationEntitiesRoadDisruptionLine) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMultiLineString(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesRoadDisruptionLine) contextValidateMultiLineString(ctx context.Context, formats strfmt.Registry) error {

	if m.MultiLineString != nil {

		if swag.IsZero(m.MultiLineString) { // not required
			return nil
		}

		if err := m.MultiLineString.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("multiLineString")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("multiLineString")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesRoadDisruptionLine) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesRoadDisruptionLine) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesRoadDisruptionLine
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
