// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesMatchedStop tfl Api presentation entities matched stop
//
// swagger:model Tfl.Api.Presentation.Entities.MatchedStop
type TflAPIPresentationEntitiesMatchedStop struct {

	// accessibility summary
	AccessibilitySummary string `json:"accessibilitySummary,omitempty"`

	// direction
	Direction string `json:"direction,omitempty"`

	// has disruption
	HasDisruption bool `json:"hasDisruption,omitempty"`

	// ics Id
	IcsID string `json:"icsId,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// lat
	Lat float64 `json:"lat,omitempty"`

	// lines
	Lines []*TflAPIPresentationEntitiesIdentifier `json:"lines"`

	// lon
	Lon float64 `json:"lon,omitempty"`

	// modes
	Modes []string `json:"modes"`

	// name
	Name string `json:"name,omitempty"`

	// parent Id
	ParentID string `json:"parentId,omitempty"`

	// route Id
	RouteID int32 `json:"routeId,omitempty"`

	// station Id
	StationID string `json:"stationId,omitempty"`

	// status
	Status bool `json:"status,omitempty"`

	// stop letter
	StopLetter string `json:"stopLetter,omitempty"`

	// stop type
	StopType string `json:"stopType,omitempty"`

	// top most parent Id
	TopMostParentID string `json:"topMostParentId,omitempty"`

	// towards
	Towards string `json:"towards,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// zone
	Zone string `json:"zone,omitempty"`
}

// Validate validates this tfl Api presentation entities matched stop
func (m *TflAPIPresentationEntitiesMatchedStop) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLines(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesMatchedStop) validateLines(formats strfmt.Registry) error {
	if swag.IsZero(m.Lines) { // not required
		return nil
	}

	for i := 0; i < len(m.Lines); i++ {
		if swag.IsZero(m.Lines[i]) { // not required
			continue
		}

		if m.Lines[i] != nil {
			if err := m.Lines[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("lines" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("lines" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this tfl Api presentation entities matched stop based on the context it is used
func (m *TflAPIPresentationEntitiesMatchedStop) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLines(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesMatchedStop) contextValidateLines(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Lines); i++ {

		if m.Lines[i] != nil {

			if swag.IsZero(m.Lines[i]) { // not required
				return nil
			}

			if err := m.Lines[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("lines" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("lines" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesMatchedStop) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesMatchedStop) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesMatchedStop
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
