// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TflAPIPresentationEntitiesFaresFaresPeriod tfl Api presentation entities fares fares period
//
// swagger:model Tfl.Api.Presentation.Entities.Fares.FaresPeriod
type TflAPIPresentationEntitiesFaresFaresPeriod struct {

	// end date
	// Format: date-time
	EndDate strfmt.DateTime `json:"endDate,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// is future
	IsFuture bool `json:"isFuture,omitempty"`

	// start date
	// Format: date-time
	StartDate strfmt.DateTime `json:"startDate,omitempty"`

	// viewable date
	// Format: date-time
	ViewableDate strfmt.DateTime `json:"viewableDate,omitempty"`
}

// Validate validates this tfl Api presentation entities fares fares period
func (m *TflAPIPresentationEntitiesFaresFaresPeriod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateViewableDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesFaresFaresPeriod) validateEndDate(formats strfmt.Registry) error {
	if swag.IsZero(m.EndDate) { // not required
		return nil
	}

	if err := validate.FormatOf("endDate", "body", "date-time", m.EndDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TflAPIPresentationEntitiesFaresFaresPeriod) validateStartDate(formats strfmt.Registry) error {
	if swag.IsZero(m.StartDate) { // not required
		return nil
	}

	if err := validate.FormatOf("startDate", "body", "date-time", m.StartDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TflAPIPresentationEntitiesFaresFaresPeriod) validateViewableDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ViewableDate) { // not required
		return nil
	}

	if err := validate.FormatOf("viewableDate", "body", "date-time", m.ViewableDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this tfl Api presentation entities fares fares period based on context it is used
func (m *TflAPIPresentationEntitiesFaresFaresPeriod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesFaresFaresPeriod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesFaresFaresPeriod) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesFaresFaresPeriod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
