// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesLineServiceTypeInfo tfl Api presentation entities line service type info
//
// swagger:model Tfl.Api.Presentation.Entities.LineServiceTypeInfo
type TflAPIPresentationEntitiesLineServiceTypeInfo struct {

	// name
	Name string `json:"name,omitempty"`

	// uri
	URI string `json:"uri,omitempty"`
}

// Validate validates this tfl Api presentation entities line service type info
func (m *TflAPIPresentationEntitiesLineServiceTypeInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tfl Api presentation entities line service type info based on context it is used
func (m *TflAPIPresentationEntitiesLineServiceTypeInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesLineServiceTypeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesLineServiceTypeInfo) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesLineServiceTypeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
