// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TflAPICommonGeoPoint tfl Api common geo point
//
// swagger:model Tfl.Api.Common.GeoPoint
type TflAPICommonGeoPoint struct {

	// lat
	// Required: true
	Lat *float64 `json:"lat"`

	// lon
	// Required: true
	Lon *float64 `json:"lon"`
}

// Validate validates this tfl Api common geo point
func (m *TflAPICommonGeoPoint) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLon(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPICommonGeoPoint) validateLat(formats strfmt.Registry) error {

	if err := validate.Required("lat", "body", m.Lat); err != nil {
		return err
	}

	return nil
}

func (m *TflAPICommonGeoPoint) validateLon(formats strfmt.Registry) error {

	if err := validate.Required("lon", "body", m.Lon); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this tfl Api common geo point based on context it is used
func (m *TflAPICommonGeoPoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TflAPICommonGeoPoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPICommonGeoPoint) UnmarshalBinary(b []byte) error {
	var res TflAPICommonGeoPoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
