// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesBikePointOccupancy Bike point occupancy
//
// swagger:model Tfl.Api.Presentation.Entities.BikePointOccupancy
type TflAPIPresentationEntitiesBikePointOccupancy struct {

	// Total bike counts
	BikesCount int32 `json:"bikesCount,omitempty"`

	// Total ebikes count
	EBikesCount int32 `json:"eBikesCount,omitempty"`

	// Empty docks
	EmptyDocks int32 `json:"emptyDocks,omitempty"`

	// Id of the bike point such as BikePoints_1
	ID string `json:"id,omitempty"`

	// Name / Common name of the bike point
	Name string `json:"name,omitempty"`

	// Total standard bikes count
	StandardBikesCount int32 `json:"standardBikesCount,omitempty"`

	// Total docks available
	TotalDocks int32 `json:"totalDocks,omitempty"`
}

// Validate validates this tfl Api presentation entities bike point occupancy
func (m *TflAPIPresentationEntitiesBikePointOccupancy) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tfl Api presentation entities bike point occupancy based on context it is used
func (m *TflAPIPresentationEntitiesBikePointOccupancy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesBikePointOccupancy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesBikePointOccupancy) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesBikePointOccupancy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
