// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TflAPICommonJourneyPlannerJpElevation tfl Api common journey planner jp elevation
//
// swagger:model Tfl.Api.Common.JourneyPlanner.JpElevation
type TflAPICommonJourneyPlannerJpElevation struct {

	// distance
	Distance int32 `json:"distance,omitempty"`

	// end lat
	EndLat float64 `json:"endLat,omitempty"`

	// end lon
	EndLon float64 `json:"endLon,omitempty"`

	// gradient
	Gradient float64 `json:"gradient,omitempty"`

	// height from previous point
	HeightFromPreviousPoint int32 `json:"heightFromPreviousPoint,omitempty"`

	// start elevation
	StartElevation int32 `json:"startElevation,omitempty"`

	// start lat
	StartLat float64 `json:"startLat,omitempty"`

	// start lon
	StartLon float64 `json:"startLon,omitempty"`
}

// Validate validates this tfl Api common journey planner jp elevation
func (m *TflAPICommonJourneyPlannerJpElevation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tfl Api common journey planner jp elevation based on context it is used
func (m *TflAPICommonJourneyPlannerJpElevation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TflAPICommonJourneyPlannerJpElevation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPICommonJourneyPlannerJpElevation) UnmarshalBinary(b []byte) error {
	var res TflAPICommonJourneyPlannerJpElevation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
