// Code generated by go-swagger; DO NOT EDIT.

package bike_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBikePointSearchParams creates a new BikePointSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBikePointSearchParams() *BikePointSearchParams {
	return &BikePointSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBikePointSearchParamsWithTimeout creates a new BikePointSearchParams object
// with the ability to set a timeout on a request.
func NewBikePointSearchParamsWithTimeout(timeout time.Duration) *BikePointSearchParams {
	return &BikePointSearchParams{
		timeout: timeout,
	}
}

// NewBikePointSearchParamsWithContext creates a new BikePointSearchParams object
// with the ability to set a context for a request.
func NewBikePointSearchParamsWithContext(ctx context.Context) *BikePointSearchParams {
	return &BikePointSearchParams{
		Context: ctx,
	}
}

// NewBikePointSearchParamsWithHTTPClient creates a new BikePointSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewBikePointSearchParamsWithHTTPClient(client *http.Client) *BikePointSearchParams {
	return &BikePointSearchParams{
		HTTPClient: client,
	}
}

/*
BikePointSearchParams contains all the parameters to send to the API endpoint

	for the bike point search operation.

	Typically these are written to a http.Request.
*/
type BikePointSearchParams struct {

	/* Query.

	   The search term e.g. "St. James"
	*/
	Query string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bike point search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BikePointSearchParams) WithDefaults() *BikePointSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bike point search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BikePointSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bike point search params
func (o *BikePointSearchParams) WithTimeout(timeout time.Duration) *BikePointSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bike point search params
func (o *BikePointSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bike point search params
func (o *BikePointSearchParams) WithContext(ctx context.Context) *BikePointSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bike point search params
func (o *BikePointSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bike point search params
func (o *BikePointSearchParams) WithHTTPClient(client *http.Client) *BikePointSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bike point search params
func (o *BikePointSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the bike point search params
func (o *BikePointSearchParams) WithQuery(query string) *BikePointSearchParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the bike point search params
func (o *BikePointSearchParams) SetQuery(query string) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *BikePointSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param query
	qrQuery := o.Query
	qQuery := qrQuery
	if qQuery != "" {

		if err := r.SetQueryParam("query", qQuery); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
