// Code generated by go-swagger; DO NOT EDIT.

package bike_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// BikePointSearchReader is a Reader for the BikePointSearch structure.
type BikePointSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BikePointSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewBikePointSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /BikePoint/Search] BikePoint_Search", response, response.Code())
	}
}

// NewBikePointSearchOK creates a BikePointSearchOK with default headers values
func NewBikePointSearchOK() *BikePointSearchOK {
	return &BikePointSearchOK{}
}

/*
BikePointSearchOK describes a response with status code 200, with default header values.

OK
*/
type BikePointSearchOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlace
}

// IsSuccess returns true when this bike point search o k response has a 2xx status code
func (o *BikePointSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this bike point search o k response has a 3xx status code
func (o *BikePointSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bike point search o k response has a 4xx status code
func (o *BikePointSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this bike point search o k response has a 5xx status code
func (o *BikePointSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this bike point search o k response a status code equal to that given
func (o *BikePointSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the bike point search o k response
func (o *BikePointSearchOK) Code() int {
	return 200
}

func (o *BikePointSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /BikePoint/Search][%d] bikePointSearchOK %s", 200, payload)
}

func (o *BikePointSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /BikePoint/Search][%d] bikePointSearchOK %s", 200, payload)
}

func (o *BikePointSearchOK) GetPayload() []*models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *BikePointSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
