// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSearchMetaSortsParams creates a new SearchMetaSortsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchMetaSortsParams() *SearchMetaSortsParams {
	return &SearchMetaSortsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchMetaSortsParamsWithTimeout creates a new SearchMetaSortsParams object
// with the ability to set a timeout on a request.
func NewSearchMetaSortsParamsWithTimeout(timeout time.Duration) *SearchMetaSortsParams {
	return &SearchMetaSortsParams{
		timeout: timeout,
	}
}

// NewSearchMetaSortsParamsWithContext creates a new SearchMetaSortsParams object
// with the ability to set a context for a request.
func NewSearchMetaSortsParamsWithContext(ctx context.Context) *SearchMetaSortsParams {
	return &SearchMetaSortsParams{
		Context: ctx,
	}
}

// NewSearchMetaSortsParamsWithHTTPClient creates a new SearchMetaSortsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchMetaSortsParamsWithHTTPClient(client *http.Client) *SearchMetaSortsParams {
	return &SearchMetaSortsParams{
		HTTPClient: client,
	}
}

/*
SearchMetaSortsParams contains all the parameters to send to the API endpoint

	for the search meta sorts operation.

	Typically these are written to a http.Request.
*/
type SearchMetaSortsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search meta sorts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchMetaSortsParams) WithDefaults() *SearchMetaSortsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search meta sorts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchMetaSortsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search meta sorts params
func (o *SearchMetaSortsParams) WithTimeout(timeout time.Duration) *SearchMetaSortsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search meta sorts params
func (o *SearchMetaSortsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search meta sorts params
func (o *SearchMetaSortsParams) WithContext(ctx context.Context) *SearchMetaSortsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search meta sorts params
func (o *SearchMetaSortsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search meta sorts params
func (o *SearchMetaSortsParams) WithHTTPClient(client *http.Client) *SearchMetaSortsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search meta sorts params
func (o *SearchMetaSortsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SearchMetaSortsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
