// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// SearchGetReader is a Reader for the SearchGet structure.
type SearchGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSearchGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Search] Search_Get", response, response.Code())
	}
}

// NewSearchGetOK creates a SearchGetOK with default headers values
func NewSearchGetOK() *SearchGetOK {
	return &SearchGetOK{}
}

/*
SearchGetOK describes a response with status code 200, with default header values.

OK
*/
type SearchGetOK struct {
	Payload *models.TflAPIPresentationEntitiesSearchResponse
}

// IsSuccess returns true when this search get o k response has a 2xx status code
func (o *SearchGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search get o k response has a 3xx status code
func (o *SearchGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search get o k response has a 4xx status code
func (o *SearchGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search get o k response has a 5xx status code
func (o *SearchGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search get o k response a status code equal to that given
func (o *SearchGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search get o k response
func (o *SearchGetOK) Code() int {
	return 200
}

func (o *SearchGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Search][%d] searchGetOK %s", 200, payload)
}

func (o *SearchGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Search][%d] searchGetOK %s", 200, payload)
}

func (o *SearchGetOK) GetPayload() *models.TflAPIPresentationEntitiesSearchResponse {
	return o.Payload
}

func (o *SearchGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesSearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
