// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SearchMetaSearchProvidersReader is a Reader for the SearchMetaSearchProviders structure.
type SearchMetaSearchProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchMetaSearchProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSearchMetaSearchProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Search/Meta/SearchProviders] Search_MetaSearchProviders", response, response.Code())
	}
}

// NewSearchMetaSearchProvidersOK creates a SearchMetaSearchProvidersOK with default headers values
func NewSearchMetaSearchProvidersOK() *SearchMetaSearchProvidersOK {
	return &SearchMetaSearchProvidersOK{}
}

/*
SearchMetaSearchProvidersOK describes a response with status code 200, with default header values.

OK
*/
type SearchMetaSearchProvidersOK struct {
	Payload []string
}

// IsSuccess returns true when this search meta search providers o k response has a 2xx status code
func (o *SearchMetaSearchProvidersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search meta search providers o k response has a 3xx status code
func (o *SearchMetaSearchProvidersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search meta search providers o k response has a 4xx status code
func (o *SearchMetaSearchProvidersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search meta search providers o k response has a 5xx status code
func (o *SearchMetaSearchProvidersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search meta search providers o k response a status code equal to that given
func (o *SearchMetaSearchProvidersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search meta search providers o k response
func (o *SearchMetaSearchProvidersOK) Code() int {
	return 200
}

func (o *SearchMetaSearchProvidersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Search/Meta/SearchProviders][%d] searchMetaSearchProvidersOK %s", 200, payload)
}

func (o *SearchMetaSearchProvidersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Search/Meta/SearchProviders][%d] searchMetaSearchProvidersOK %s", 200, payload)
}

func (o *SearchMetaSearchProvidersOK) GetPayload() []string {
	return o.Payload
}

func (o *SearchMetaSearchProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
