// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointGetReader is a Reader for the StopPointGet structure.
type StopPointGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/{ids}] StopPoint_Get", response, response.Code())
	}
}

// NewStopPointGetOK creates a StopPointGetOK with default headers values
func NewStopPointGetOK() *StopPointGetOK {
	return &StopPointGetOK{}
}

/*
StopPointGetOK describes a response with status code 200, with default header values.

OK
*/
type StopPointGetOK struct {
	Payload []*models.TflAPIPresentationEntitiesStopPoint
}

// IsSuccess returns true when this stop point get o k response has a 2xx status code
func (o *StopPointGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point get o k response has a 3xx status code
func (o *StopPointGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point get o k response has a 4xx status code
func (o *StopPointGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point get o k response has a 5xx status code
func (o *StopPointGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point get o k response a status code equal to that given
func (o *StopPointGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point get o k response
func (o *StopPointGetOK) Code() int {
	return 200
}

func (o *StopPointGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/{ids}][%d] stopPointGetOK %s", 200, payload)
}

func (o *StopPointGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/{ids}][%d] stopPointGetOK %s", 200, payload)
}

func (o *StopPointGetOK) GetPayload() []*models.TflAPIPresentationEntitiesStopPoint {
	return o.Payload
}

func (o *StopPointGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
