// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStopPointArrivalDeparturesParams creates a new StopPointArrivalDeparturesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopPointArrivalDeparturesParams() *StopPointArrivalDeparturesParams {
	return &StopPointArrivalDeparturesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopPointArrivalDeparturesParamsWithTimeout creates a new StopPointArrivalDeparturesParams object
// with the ability to set a timeout on a request.
func NewStopPointArrivalDeparturesParamsWithTimeout(timeout time.Duration) *StopPointArrivalDeparturesParams {
	return &StopPointArrivalDeparturesParams{
		timeout: timeout,
	}
}

// NewStopPointArrivalDeparturesParamsWithContext creates a new StopPointArrivalDeparturesParams object
// with the ability to set a context for a request.
func NewStopPointArrivalDeparturesParamsWithContext(ctx context.Context) *StopPointArrivalDeparturesParams {
	return &StopPointArrivalDeparturesParams{
		Context: ctx,
	}
}

// NewStopPointArrivalDeparturesParamsWithHTTPClient creates a new StopPointArrivalDeparturesParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopPointArrivalDeparturesParamsWithHTTPClient(client *http.Client) *StopPointArrivalDeparturesParams {
	return &StopPointArrivalDeparturesParams{
		HTTPClient: client,
	}
}

/*
StopPointArrivalDeparturesParams contains all the parameters to send to the API endpoint

	for the stop point arrival departures operation.

	Typically these are written to a http.Request.
*/
type StopPointArrivalDeparturesParams struct {

	/* ID.

	   A StopPoint id (station naptan code e.g. 940GZZLUASL, you can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name)
	*/
	ID string

	/* LineIds.

	   A comma-separated list of line ids e.g. elizabeth, london-overground, thameslink
	*/
	LineIds []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop point arrival departures params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopPointArrivalDeparturesParams) WithDefaults() *StopPointArrivalDeparturesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop point arrival departures params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopPointArrivalDeparturesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) WithTimeout(timeout time.Duration) *StopPointArrivalDeparturesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) WithContext(ctx context.Context) *StopPointArrivalDeparturesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) WithHTTPClient(client *http.Client) *StopPointArrivalDeparturesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) WithID(id string) *StopPointArrivalDeparturesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) SetID(id string) {
	o.ID = id
}

// WithLineIds adds the lineIds to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) WithLineIds(lineIds []string) *StopPointArrivalDeparturesParams {
	o.SetLineIds(lineIds)
	return o
}

// SetLineIds adds the lineIds to the stop point arrival departures params
func (o *StopPointArrivalDeparturesParams) SetLineIds(lineIds []string) {
	o.LineIds = lineIds
}

// WriteToRequest writes these params to a swagger request
func (o *StopPointArrivalDeparturesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.LineIds != nil {

		// binding items for lineIds
		joinedLineIds := o.bindParamLineIds(reg)

		// query array param lineIds
		if err := r.SetQueryParam("lineIds", joinedLineIds...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamStopPointArrivalDepartures binds the parameter lineIds
func (o *StopPointArrivalDeparturesParams) bindParamLineIds(formats strfmt.Registry) []string {
	lineIdsIR := o.LineIds

	var lineIdsIC []string
	for _, lineIdsIIR := range lineIdsIR { // explode []string

		lineIdsIIV := lineIdsIIR // string as string
		lineIdsIC = append(lineIdsIC, lineIdsIIV)
	}

	// items.CollectionFormat: "multi"
	lineIdsIS := swag.JoinByFormat(lineIdsIC, "multi")

	return lineIdsIS
}
