// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointMetaModesReader is a Reader for the StopPointMetaModes structure.
type StopPointMetaModesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointMetaModesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointMetaModesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/Meta/Modes] StopPoint_MetaModes", response, response.Code())
	}
}

// NewStopPointMetaModesOK creates a StopPointMetaModesOK with default headers values
func NewStopPointMetaModesOK() *StopPointMetaModesOK {
	return &StopPointMetaModesOK{}
}

/*
StopPointMetaModesOK describes a response with status code 200, with default header values.

OK
*/
type StopPointMetaModesOK struct {
	Payload []*models.TflAPIPresentationEntitiesMode
}

// IsSuccess returns true when this stop point meta modes o k response has a 2xx status code
func (o *StopPointMetaModesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point meta modes o k response has a 3xx status code
func (o *StopPointMetaModesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point meta modes o k response has a 4xx status code
func (o *StopPointMetaModesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point meta modes o k response has a 5xx status code
func (o *StopPointMetaModesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point meta modes o k response a status code equal to that given
func (o *StopPointMetaModesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point meta modes o k response
func (o *StopPointMetaModesOK) Code() int {
	return 200
}

func (o *StopPointMetaModesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Meta/Modes][%d] stopPointMetaModesOK %s", 200, payload)
}

func (o *StopPointMetaModesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Meta/Modes][%d] stopPointMetaModesOK %s", 200, payload)
}

func (o *StopPointMetaModesOK) GetPayload() []*models.TflAPIPresentationEntitiesMode {
	return o.Payload
}

func (o *StopPointMetaModesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
