// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointMetaCategoriesReader is a Reader for the StopPointMetaCategories structure.
type StopPointMetaCategoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointMetaCategoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointMetaCategoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/Meta/Categories] StopPoint_MetaCategories", response, response.Code())
	}
}

// NewStopPointMetaCategoriesOK creates a StopPointMetaCategoriesOK with default headers values
func NewStopPointMetaCategoriesOK() *StopPointMetaCategoriesOK {
	return &StopPointMetaCategoriesOK{}
}

/*
StopPointMetaCategoriesOK describes a response with status code 200, with default header values.

OK
*/
type StopPointMetaCategoriesOK struct {
	Payload []*models.TflAPIPresentationEntitiesStopPointCategory
}

// IsSuccess returns true when this stop point meta categories o k response has a 2xx status code
func (o *StopPointMetaCategoriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point meta categories o k response has a 3xx status code
func (o *StopPointMetaCategoriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point meta categories o k response has a 4xx status code
func (o *StopPointMetaCategoriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point meta categories o k response has a 5xx status code
func (o *StopPointMetaCategoriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point meta categories o k response a status code equal to that given
func (o *StopPointMetaCategoriesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point meta categories o k response
func (o *StopPointMetaCategoriesOK) Code() int {
	return 200
}

func (o *StopPointMetaCategoriesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Meta/Categories][%d] stopPointMetaCategoriesOK %s", 200, payload)
}

func (o *StopPointMetaCategoriesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Meta/Categories][%d] stopPointMetaCategoriesOK %s", 200, payload)
}

func (o *StopPointMetaCategoriesOK) GetPayload() []*models.TflAPIPresentationEntitiesStopPointCategory {
	return o.Payload
}

func (o *StopPointMetaCategoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
