// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStopPointReachableFromParams creates a new StopPointReachableFromParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopPointReachableFromParams() *StopPointReachableFromParams {
	return &StopPointReachableFromParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopPointReachableFromParamsWithTimeout creates a new StopPointReachableFromParams object
// with the ability to set a timeout on a request.
func NewStopPointReachableFromParamsWithTimeout(timeout time.Duration) *StopPointReachableFromParams {
	return &StopPointReachableFromParams{
		timeout: timeout,
	}
}

// NewStopPointReachableFromParamsWithContext creates a new StopPointReachableFromParams object
// with the ability to set a context for a request.
func NewStopPointReachableFromParamsWithContext(ctx context.Context) *StopPointReachableFromParams {
	return &StopPointReachableFromParams{
		Context: ctx,
	}
}

// NewStopPointReachableFromParamsWithHTTPClient creates a new StopPointReachableFromParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopPointReachableFromParamsWithHTTPClient(client *http.Client) *StopPointReachableFromParams {
	return &StopPointReachableFromParams{
		HTTPClient: client,
	}
}

/*
StopPointReachableFromParams contains all the parameters to send to the API endpoint

	for the stop point reachable from operation.

	Typically these are written to a http.Request.
*/
type StopPointReachableFromParams struct {

	/* ID.

	   The id (station naptan code e.g. 940GZZLUASL, you can use /StopPoint/Search/{query} endpoint to find a stop point id from a station name) of the stop point to filter by
	*/
	ID string

	/* LineID.

	   Line id of the line to filter by (e.g. victoria)
	*/
	LineID string

	/* ServiceTypes.

	   A comma-separated list of service types to filter on. If not specified. Supported values: Regular, Night. Defaulted to 'Regular' if not specified
	*/
	ServiceTypes []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop point reachable from params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopPointReachableFromParams) WithDefaults() *StopPointReachableFromParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop point reachable from params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopPointReachableFromParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop point reachable from params
func (o *StopPointReachableFromParams) WithTimeout(timeout time.Duration) *StopPointReachableFromParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop point reachable from params
func (o *StopPointReachableFromParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop point reachable from params
func (o *StopPointReachableFromParams) WithContext(ctx context.Context) *StopPointReachableFromParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop point reachable from params
func (o *StopPointReachableFromParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop point reachable from params
func (o *StopPointReachableFromParams) WithHTTPClient(client *http.Client) *StopPointReachableFromParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop point reachable from params
func (o *StopPointReachableFromParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the stop point reachable from params
func (o *StopPointReachableFromParams) WithID(id string) *StopPointReachableFromParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the stop point reachable from params
func (o *StopPointReachableFromParams) SetID(id string) {
	o.ID = id
}

// WithLineID adds the lineID to the stop point reachable from params
func (o *StopPointReachableFromParams) WithLineID(lineID string) *StopPointReachableFromParams {
	o.SetLineID(lineID)
	return o
}

// SetLineID adds the lineId to the stop point reachable from params
func (o *StopPointReachableFromParams) SetLineID(lineID string) {
	o.LineID = lineID
}

// WithServiceTypes adds the serviceTypes to the stop point reachable from params
func (o *StopPointReachableFromParams) WithServiceTypes(serviceTypes []string) *StopPointReachableFromParams {
	o.SetServiceTypes(serviceTypes)
	return o
}

// SetServiceTypes adds the serviceTypes to the stop point reachable from params
func (o *StopPointReachableFromParams) SetServiceTypes(serviceTypes []string) {
	o.ServiceTypes = serviceTypes
}

// WriteToRequest writes these params to a swagger request
func (o *StopPointReachableFromParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param lineId
	if err := r.SetPathParam("lineId", o.LineID); err != nil {
		return err
	}

	if o.ServiceTypes != nil {

		// binding items for serviceTypes
		joinedServiceTypes := o.bindParamServiceTypes(reg)

		// query array param serviceTypes
		if err := r.SetQueryParam("serviceTypes", joinedServiceTypes...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamStopPointReachableFrom binds the parameter serviceTypes
func (o *StopPointReachableFromParams) bindParamServiceTypes(formats strfmt.Registry) []string {
	serviceTypesIR := o.ServiceTypes

	var serviceTypesIC []string
	for _, serviceTypesIIR := range serviceTypesIR { // explode []string

		serviceTypesIIV := serviceTypesIIR // string as string
		serviceTypesIC = append(serviceTypesIC, serviceTypesIIV)
	}

	// items.CollectionFormat: "multi"
	serviceTypesIS := swag.JoinByFormat(serviceTypesIC, "multi")

	return serviceTypesIS
}
