// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointSearchReader is a Reader for the StopPointSearch structure.
type StopPointSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/Search/{query}] StopPoint_Search", response, response.Code())
	}
}

// NewStopPointSearchOK creates a StopPointSearchOK with default headers values
func NewStopPointSearchOK() *StopPointSearchOK {
	return &StopPointSearchOK{}
}

/*
StopPointSearchOK describes a response with status code 200, with default header values.

OK
*/
type StopPointSearchOK struct {
	Payload *models.TflAPIPresentationEntitiesSearchResponse
}

// IsSuccess returns true when this stop point search o k response has a 2xx status code
func (o *StopPointSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point search o k response has a 3xx status code
func (o *StopPointSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point search o k response has a 4xx status code
func (o *StopPointSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point search o k response has a 5xx status code
func (o *StopPointSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point search o k response a status code equal to that given
func (o *StopPointSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point search o k response
func (o *StopPointSearchOK) Code() int {
	return 200
}

func (o *StopPointSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Search/{query}][%d] stopPointSearchOK %s", 200, payload)
}

func (o *StopPointSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Search/{query}][%d] stopPointSearchOK %s", 200, payload)
}

func (o *StopPointSearchOK) GetPayload() *models.TflAPIPresentationEntitiesSearchResponse {
	return o.Payload
}

func (o *StopPointSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesSearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
