// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointGetByTypeWithPaginationReader is a Reader for the StopPointGetByTypeWithPagination structure.
type StopPointGetByTypeWithPaginationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetByTypeWithPaginationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetByTypeWithPaginationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/Type/{types}/page/{page}] StopPoint_GetByTypeWithPagination", response, response.Code())
	}
}

// NewStopPointGetByTypeWithPaginationOK creates a StopPointGetByTypeWithPaginationOK with default headers values
func NewStopPointGetByTypeWithPaginationOK() *StopPointGetByTypeWithPaginationOK {
	return &StopPointGetByTypeWithPaginationOK{}
}

/*
StopPointGetByTypeWithPaginationOK describes a response with status code 200, with default header values.

OK
*/
type StopPointGetByTypeWithPaginationOK struct {
	Payload []*models.TflAPIPresentationEntitiesStopPoint
}

// IsSuccess returns true when this stop point get by type with pagination o k response has a 2xx status code
func (o *StopPointGetByTypeWithPaginationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point get by type with pagination o k response has a 3xx status code
func (o *StopPointGetByTypeWithPaginationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point get by type with pagination o k response has a 4xx status code
func (o *StopPointGetByTypeWithPaginationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point get by type with pagination o k response has a 5xx status code
func (o *StopPointGetByTypeWithPaginationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point get by type with pagination o k response a status code equal to that given
func (o *StopPointGetByTypeWithPaginationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point get by type with pagination o k response
func (o *StopPointGetByTypeWithPaginationOK) Code() int {
	return 200
}

func (o *StopPointGetByTypeWithPaginationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Type/{types}/page/{page}][%d] stopPointGetByTypeWithPaginationOK %s", 200, payload)
}

func (o *StopPointGetByTypeWithPaginationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Type/{types}/page/{page}][%d] stopPointGetByTypeWithPaginationOK %s", 200, payload)
}

func (o *StopPointGetByTypeWithPaginationOK) GetPayload() []*models.TflAPIPresentationEntitiesStopPoint {
	return o.Payload
}

func (o *StopPointGetByTypeWithPaginationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
