// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointCrowdingReader is a Reader for the StopPointCrowding structure.
type StopPointCrowdingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointCrowdingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointCrowdingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/{id}/Crowding/{line}] StopPoint_Crowding", response, response.Code())
	}
}

// NewStopPointCrowdingOK creates a StopPointCrowdingOK with default headers values
func NewStopPointCrowdingOK() *StopPointCrowdingOK {
	return &StopPointCrowdingOK{}
}

/*
StopPointCrowdingOK describes a response with status code 200, with default header values.

OK
*/
type StopPointCrowdingOK struct {
	Payload []*models.TflAPIPresentationEntitiesStopPoint
}

// IsSuccess returns true when this stop point crowding o k response has a 2xx status code
func (o *StopPointCrowdingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point crowding o k response has a 3xx status code
func (o *StopPointCrowdingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point crowding o k response has a 4xx status code
func (o *StopPointCrowdingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point crowding o k response has a 5xx status code
func (o *StopPointCrowdingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point crowding o k response a status code equal to that given
func (o *StopPointCrowdingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point crowding o k response
func (o *StopPointCrowdingOK) Code() int {
	return 200
}

func (o *StopPointCrowdingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/{id}/Crowding/{line}][%d] stopPointCrowdingOK %s", 200, payload)
}

func (o *StopPointCrowdingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/{id}/Crowding/{line}][%d] stopPointCrowdingOK %s", 200, payload)
}

func (o *StopPointCrowdingOK) GetPayload() []*models.TflAPIPresentationEntitiesStopPoint {
	return o.Payload
}

func (o *StopPointCrowdingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
