// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopPointMetaModesParams creates a new StopPointMetaModesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopPointMetaModesParams() *StopPointMetaModesParams {
	return &StopPointMetaModesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopPointMetaModesParamsWithTimeout creates a new StopPointMetaModesParams object
// with the ability to set a timeout on a request.
func NewStopPointMetaModesParamsWithTimeout(timeout time.Duration) *StopPointMetaModesParams {
	return &StopPointMetaModesParams{
		timeout: timeout,
	}
}

// NewStopPointMetaModesParamsWithContext creates a new StopPointMetaModesParams object
// with the ability to set a context for a request.
func NewStopPointMetaModesParamsWithContext(ctx context.Context) *StopPointMetaModesParams {
	return &StopPointMetaModesParams{
		Context: ctx,
	}
}

// NewStopPointMetaModesParamsWithHTTPClient creates a new StopPointMetaModesParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopPointMetaModesParamsWithHTTPClient(client *http.Client) *StopPointMetaModesParams {
	return &StopPointMetaModesParams{
		HTTPClient: client,
	}
}

/*
StopPointMetaModesParams contains all the parameters to send to the API endpoint

	for the stop point meta modes operation.

	Typically these are written to a http.Request.
*/
type StopPointMetaModesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop point meta modes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopPointMetaModesParams) WithDefaults() *StopPointMetaModesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop point meta modes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopPointMetaModesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop point meta modes params
func (o *StopPointMetaModesParams) WithTimeout(timeout time.Duration) *StopPointMetaModesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop point meta modes params
func (o *StopPointMetaModesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop point meta modes params
func (o *StopPointMetaModesParams) WithContext(ctx context.Context) *StopPointMetaModesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop point meta modes params
func (o *StopPointMetaModesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop point meta modes params
func (o *StopPointMetaModesParams) WithHTTPClient(client *http.Client) *StopPointMetaModesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop point meta modes params
func (o *StopPointMetaModesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StopPointMetaModesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
