// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointGetTaxiRanksByIdsReader is a Reader for the StopPointGetTaxiRanksByIds structure.
type StopPointGetTaxiRanksByIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetTaxiRanksByIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetTaxiRanksByIdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/{stopPointId}/TaxiRanks] StopPoint_GetTaxiRanksByIds", response, response.Code())
	}
}

// NewStopPointGetTaxiRanksByIdsOK creates a StopPointGetTaxiRanksByIdsOK with default headers values
func NewStopPointGetTaxiRanksByIdsOK() *StopPointGetTaxiRanksByIdsOK {
	return &StopPointGetTaxiRanksByIdsOK{}
}

/*
StopPointGetTaxiRanksByIdsOK describes a response with status code 200, with default header values.

OK
*/
type StopPointGetTaxiRanksByIdsOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlace
}

// IsSuccess returns true when this stop point get taxi ranks by ids o k response has a 2xx status code
func (o *StopPointGetTaxiRanksByIdsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point get taxi ranks by ids o k response has a 3xx status code
func (o *StopPointGetTaxiRanksByIdsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point get taxi ranks by ids o k response has a 4xx status code
func (o *StopPointGetTaxiRanksByIdsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point get taxi ranks by ids o k response has a 5xx status code
func (o *StopPointGetTaxiRanksByIdsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point get taxi ranks by ids o k response a status code equal to that given
func (o *StopPointGetTaxiRanksByIdsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point get taxi ranks by ids o k response
func (o *StopPointGetTaxiRanksByIdsOK) Code() int {
	return 200
}

func (o *StopPointGetTaxiRanksByIdsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/{stopPointId}/TaxiRanks][%d] stopPointGetTaxiRanksByIdsOK %s", 200, payload)
}

func (o *StopPointGetTaxiRanksByIdsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/{stopPointId}/TaxiRanks][%d] stopPointGetTaxiRanksByIdsOK %s", 200, payload)
}

func (o *StopPointGetTaxiRanksByIdsOK) GetPayload() []*models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *StopPointGetTaxiRanksByIdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
