// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointGetByModeReader is a Reader for the StopPointGetByMode structure.
type StopPointGetByModeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetByModeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetByModeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/Mode/{modes}] StopPoint_GetByMode", response, response.Code())
	}
}

// NewStopPointGetByModeOK creates a StopPointGetByModeOK with default headers values
func NewStopPointGetByModeOK() *StopPointGetByModeOK {
	return &StopPointGetByModeOK{}
}

/*
StopPointGetByModeOK describes a response with status code 200, with default header values.

OK
*/
type StopPointGetByModeOK struct {
	Payload *models.TflAPIPresentationEntitiesStopPointsResponse
}

// IsSuccess returns true when this stop point get by mode o k response has a 2xx status code
func (o *StopPointGetByModeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point get by mode o k response has a 3xx status code
func (o *StopPointGetByModeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point get by mode o k response has a 4xx status code
func (o *StopPointGetByModeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point get by mode o k response has a 5xx status code
func (o *StopPointGetByModeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point get by mode o k response a status code equal to that given
func (o *StopPointGetByModeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point get by mode o k response
func (o *StopPointGetByModeOK) Code() int {
	return 200
}

func (o *StopPointGetByModeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Mode/{modes}][%d] stopPointGetByModeOK %s", 200, payload)
}

func (o *StopPointGetByModeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Mode/{modes}][%d] stopPointGetByModeOK %s", 200, payload)
}

func (o *StopPointGetByModeOK) GetPayload() *models.TflAPIPresentationEntitiesStopPointsResponse {
	return o.Payload
}

func (o *StopPointGetByModeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesStopPointsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
