// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// StopPointDisruptionByModeReader is a Reader for the StopPointDisruptionByMode structure.
type StopPointDisruptionByModeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointDisruptionByModeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointDisruptionByModeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /StopPoint/Mode/{modes}/Disruption] StopPoint_DisruptionByMode", response, response.Code())
	}
}

// NewStopPointDisruptionByModeOK creates a StopPointDisruptionByModeOK with default headers values
func NewStopPointDisruptionByModeOK() *StopPointDisruptionByModeOK {
	return &StopPointDisruptionByModeOK{}
}

/*
StopPointDisruptionByModeOK describes a response with status code 200, with default header values.

OK
*/
type StopPointDisruptionByModeOK struct {
	Payload []*models.TflAPIPresentationEntitiesDisruptedPoint
}

// IsSuccess returns true when this stop point disruption by mode o k response has a 2xx status code
func (o *StopPointDisruptionByModeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop point disruption by mode o k response has a 3xx status code
func (o *StopPointDisruptionByModeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop point disruption by mode o k response has a 4xx status code
func (o *StopPointDisruptionByModeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop point disruption by mode o k response has a 5xx status code
func (o *StopPointDisruptionByModeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop point disruption by mode o k response a status code equal to that given
func (o *StopPointDisruptionByModeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stop point disruption by mode o k response
func (o *StopPointDisruptionByModeOK) Code() int {
	return 200
}

func (o *StopPointDisruptionByModeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Mode/{modes}/Disruption][%d] stopPointDisruptionByModeOK %s", 200, payload)
}

func (o *StopPointDisruptionByModeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /StopPoint/Mode/{modes}/Disruption][%d] stopPointDisruptionByModeOK %s", 200, payload)
}

func (o *StopPointDisruptionByModeOK) GetPayload() []*models.TflAPIPresentationEntitiesDisruptedPoint {
	return o.Payload
}

func (o *StopPointDisruptionByModeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
