// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// PlaceGetOverlayReader is a Reader for the PlaceGetOverlay structure.
type PlaceGetOverlayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceGetOverlayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceGetOverlayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Place/{type}/overlay/{z}/{Lat}/{Lon}/{width}/{height}] Place_GetOverlay", response, response.Code())
	}
}

// NewPlaceGetOverlayOK creates a PlaceGetOverlayOK with default headers values
func NewPlaceGetOverlayOK() *PlaceGetOverlayOK {
	return &PlaceGetOverlayOK{}
}

/*
PlaceGetOverlayOK describes a response with status code 200, with default header values.

OK
*/
type PlaceGetOverlayOK struct {
	Payload models.SystemObject
}

// IsSuccess returns true when this place get overlay o k response has a 2xx status code
func (o *PlaceGetOverlayOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this place get overlay o k response has a 3xx status code
func (o *PlaceGetOverlayOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this place get overlay o k response has a 4xx status code
func (o *PlaceGetOverlayOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this place get overlay o k response has a 5xx status code
func (o *PlaceGetOverlayOK) IsServerError() bool {
	return false
}

// IsCode returns true when this place get overlay o k response a status code equal to that given
func (o *PlaceGetOverlayOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the place get overlay o k response
func (o *PlaceGetOverlayOK) Code() int {
	return 200
}

func (o *PlaceGetOverlayOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place/{type}/overlay/{z}/{Lat}/{Lon}/{width}/{height}][%d] placeGetOverlayOK %s", 200, payload)
}

func (o *PlaceGetOverlayOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place/{type}/overlay/{z}/{Lat}/{Lon}/{width}/{height}][%d] placeGetOverlayOK %s", 200, payload)
}

func (o *PlaceGetOverlayOK) GetPayload() models.SystemObject {
	return o.Payload
}

func (o *PlaceGetOverlayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
