// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// PlaceSearchReader is a Reader for the PlaceSearch structure.
type PlaceSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Place/Search] Place_Search", response, response.Code())
	}
}

// NewPlaceSearchOK creates a PlaceSearchOK with default headers values
func NewPlaceSearchOK() *PlaceSearchOK {
	return &PlaceSearchOK{}
}

/*
PlaceSearchOK describes a response with status code 200, with default header values.

OK
*/
type PlaceSearchOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlace
}

// IsSuccess returns true when this place search o k response has a 2xx status code
func (o *PlaceSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this place search o k response has a 3xx status code
func (o *PlaceSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this place search o k response has a 4xx status code
func (o *PlaceSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this place search o k response has a 5xx status code
func (o *PlaceSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this place search o k response a status code equal to that given
func (o *PlaceSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the place search o k response
func (o *PlaceSearchOK) Code() int {
	return 200
}

func (o *PlaceSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place/Search][%d] placeSearchOK %s", 200, payload)
}

func (o *PlaceSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place/Search][%d] placeSearchOK %s", 200, payload)
}

func (o *PlaceSearchOK) GetPayload() []*models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *PlaceSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
