// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// PlaceGetByGeoReader is a Reader for the PlaceGetByGeo structure.
type PlaceGetByGeoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceGetByGeoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceGetByGeoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Place] Place_GetByGeo", response, response.Code())
	}
}

// NewPlaceGetByGeoOK creates a PlaceGetByGeoOK with default headers values
func NewPlaceGetByGeoOK() *PlaceGetByGeoOK {
	return &PlaceGetByGeoOK{}
}

/*
PlaceGetByGeoOK describes a response with status code 200, with default header values.

OK
*/
type PlaceGetByGeoOK struct {
	Payload []*models.TflAPIPresentationEntitiesStopPoint
}

// IsSuccess returns true when this place get by geo o k response has a 2xx status code
func (o *PlaceGetByGeoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this place get by geo o k response has a 3xx status code
func (o *PlaceGetByGeoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this place get by geo o k response has a 4xx status code
func (o *PlaceGetByGeoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this place get by geo o k response has a 5xx status code
func (o *PlaceGetByGeoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this place get by geo o k response a status code equal to that given
func (o *PlaceGetByGeoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the place get by geo o k response
func (o *PlaceGetByGeoOK) Code() int {
	return 200
}

func (o *PlaceGetByGeoOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place][%d] placeGetByGeoOK %s", 200, payload)
}

func (o *PlaceGetByGeoOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place][%d] placeGetByGeoOK %s", 200, payload)
}

func (o *PlaceGetByGeoOK) GetPayload() []*models.TflAPIPresentationEntitiesStopPoint {
	return o.Payload
}

func (o *PlaceGetByGeoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
