// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// PlaceMetaCategoriesReader is a Reader for the PlaceMetaCategories structure.
type PlaceMetaCategoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceMetaCategoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceMetaCategoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Place/Meta/Categories] Place_MetaCategories", response, response.Code())
	}
}

// NewPlaceMetaCategoriesOK creates a PlaceMetaCategoriesOK with default headers values
func NewPlaceMetaCategoriesOK() *PlaceMetaCategoriesOK {
	return &PlaceMetaCategoriesOK{}
}

/*
PlaceMetaCategoriesOK describes a response with status code 200, with default header values.

OK
*/
type PlaceMetaCategoriesOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlaceCategory
}

// IsSuccess returns true when this place meta categories o k response has a 2xx status code
func (o *PlaceMetaCategoriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this place meta categories o k response has a 3xx status code
func (o *PlaceMetaCategoriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this place meta categories o k response has a 4xx status code
func (o *PlaceMetaCategoriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this place meta categories o k response has a 5xx status code
func (o *PlaceMetaCategoriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this place meta categories o k response a status code equal to that given
func (o *PlaceMetaCategoriesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the place meta categories o k response
func (o *PlaceMetaCategoriesOK) Code() int {
	return 200
}

func (o *PlaceMetaCategoriesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place/Meta/Categories][%d] placeMetaCategoriesOK %s", 200, payload)
}

func (o *PlaceMetaCategoriesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place/Meta/Categories][%d] placeMetaCategoriesOK %s", 200, payload)
}

func (o *PlaceMetaCategoriesOK) GetPayload() []*models.TflAPIPresentationEntitiesPlaceCategory {
	return o.Payload
}

func (o *PlaceMetaCategoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
