// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// PlaceMetaPlaceTypesReader is a Reader for the PlaceMetaPlaceTypes structure.
type PlaceMetaPlaceTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceMetaPlaceTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceMetaPlaceTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Place/Meta/PlaceTypes] Place_MetaPlaceTypes", response, response.Code())
	}
}

// NewPlaceMetaPlaceTypesOK creates a PlaceMetaPlaceTypesOK with default headers values
func NewPlaceMetaPlaceTypesOK() *PlaceMetaPlaceTypesOK {
	return &PlaceMetaPlaceTypesOK{}
}

/*
PlaceMetaPlaceTypesOK describes a response with status code 200, with default header values.

OK
*/
type PlaceMetaPlaceTypesOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlaceCategory
}

// IsSuccess returns true when this place meta place types o k response has a 2xx status code
func (o *PlaceMetaPlaceTypesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this place meta place types o k response has a 3xx status code
func (o *PlaceMetaPlaceTypesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this place meta place types o k response has a 4xx status code
func (o *PlaceMetaPlaceTypesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this place meta place types o k response has a 5xx status code
func (o *PlaceMetaPlaceTypesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this place meta place types o k response a status code equal to that given
func (o *PlaceMetaPlaceTypesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the place meta place types o k response
func (o *PlaceMetaPlaceTypesOK) Code() int {
	return 200
}

func (o *PlaceMetaPlaceTypesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place/Meta/PlaceTypes][%d] placeMetaPlaceTypesOK %s", 200, payload)
}

func (o *PlaceMetaPlaceTypesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Place/Meta/PlaceTypes][%d] placeMetaPlaceTypesOK %s", 200, payload)
}

func (o *PlaceMetaPlaceTypesOK) GetPayload() []*models.TflAPIPresentationEntitiesPlaceCategory {
	return o.Payload
}

func (o *PlaceMetaPlaceTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
