// Code generated by go-swagger; DO NOT EDIT.

package occupancy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// OccupancyGetChargeConnectorStatusReader is a Reader for the OccupancyGetChargeConnectorStatus structure.
type OccupancyGetChargeConnectorStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OccupancyGetChargeConnectorStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewOccupancyGetChargeConnectorStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Occupancy/ChargeConnector/{ids}] Occupancy_GetChargeConnectorStatus", response, response.Code())
	}
}

// NewOccupancyGetChargeConnectorStatusOK creates a OccupancyGetChargeConnectorStatusOK with default headers values
func NewOccupancyGetChargeConnectorStatusOK() *OccupancyGetChargeConnectorStatusOK {
	return &OccupancyGetChargeConnectorStatusOK{}
}

/*
OccupancyGetChargeConnectorStatusOK describes a response with status code 200, with default header values.

OK
*/
type OccupancyGetChargeConnectorStatusOK struct {
	Payload []*models.TflAPIPresentationEntitiesChargeConnectorOccupancy
}

// IsSuccess returns true when this occupancy get charge connector status o k response has a 2xx status code
func (o *OccupancyGetChargeConnectorStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this occupancy get charge connector status o k response has a 3xx status code
func (o *OccupancyGetChargeConnectorStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this occupancy get charge connector status o k response has a 4xx status code
func (o *OccupancyGetChargeConnectorStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this occupancy get charge connector status o k response has a 5xx status code
func (o *OccupancyGetChargeConnectorStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this occupancy get charge connector status o k response a status code equal to that given
func (o *OccupancyGetChargeConnectorStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the occupancy get charge connector status o k response
func (o *OccupancyGetChargeConnectorStatusOK) Code() int {
	return 200
}

func (o *OccupancyGetChargeConnectorStatusOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Occupancy/ChargeConnector/{ids}][%d] occupancyGetChargeConnectorStatusOK %s", 200, payload)
}

func (o *OccupancyGetChargeConnectorStatusOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Occupancy/ChargeConnector/{ids}][%d] occupancyGetChargeConnectorStatusOK %s", 200, payload)
}

func (o *OccupancyGetChargeConnectorStatusOK) GetPayload() []*models.TflAPIPresentationEntitiesChargeConnectorOccupancy {
	return o.Payload
}

func (o *OccupancyGetChargeConnectorStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
