// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/client/accident_stats"
	"tfltt/tfl/client/air_quality"
	"tfltt/tfl/client/bike_point"
	"tfltt/tfl/client/cabwise"
	"tfltt/tfl/client/journey"
	"tfltt/tfl/client/line"
	"tfltt/tfl/client/mode"
	"tfltt/tfl/client/occupancy"
	"tfltt/tfl/client/place"
	"tfltt/tfl/client/road"
	"tfltt/tfl/client/search"
	"tfltt/tfl/client/stop_point"
	"tfltt/tfl/client/travel_time"
	"tfltt/tfl/client/vehicle"
)

// Default tfl HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.digital.tfl.gov.uk"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new tfl HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Tfl {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new tfl HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Tfl {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new tfl client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Tfl {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Tfl)
	cli.Transport = transport
	cli.AccidentStats = accident_stats.New(transport, formats)
	cli.AirQuality = air_quality.New(transport, formats)
	cli.BikePoint = bike_point.New(transport, formats)
	cli.Cabwise = cabwise.New(transport, formats)
	cli.Journey = journey.New(transport, formats)
	cli.Line = line.New(transport, formats)
	cli.Mode = mode.New(transport, formats)
	cli.Occupancy = occupancy.New(transport, formats)
	cli.Place = place.New(transport, formats)
	cli.Road = road.New(transport, formats)
	cli.Search = search.New(transport, formats)
	cli.StopPoint = stop_point.New(transport, formats)
	cli.TravelTime = travel_time.New(transport, formats)
	cli.Vehicle = vehicle.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Tfl is a client for tfl
type Tfl struct {
	AccidentStats accident_stats.ClientService

	AirQuality air_quality.ClientService

	BikePoint bike_point.ClientService

	Cabwise cabwise.ClientService

	Journey journey.ClientService

	Line line.ClientService

	Mode mode.ClientService

	Occupancy occupancy.ClientService

	Place place.ClientService

	Road road.ClientService

	Search search.ClientService

	StopPoint stop_point.ClientService

	TravelTime travel_time.ClientService

	Vehicle vehicle.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Tfl) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.AccidentStats.SetTransport(transport)
	c.AirQuality.SetTransport(transport)
	c.BikePoint.SetTransport(transport)
	c.Cabwise.SetTransport(transport)
	c.Journey.SetTransport(transport)
	c.Line.SetTransport(transport)
	c.Mode.SetTransport(transport)
	c.Occupancy.SetTransport(transport)
	c.Place.SetTransport(transport)
	c.Road.SetTransport(transport)
	c.Search.SetTransport(transport)
	c.StopPoint.SetTransport(transport)
	c.TravelTime.SetTransport(transport)
	c.Vehicle.SetTransport(transport)
}
