// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// LineGetReader is a Reader for the LineGet structure.
type LineGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewLineGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Line/{ids}] Line_Get", response, response.Code())
	}
}

// NewLineGetOK creates a LineGetOK with default headers values
func NewLineGetOK() *LineGetOK {
	return &LineGetOK{}
}

/*
LineGetOK describes a response with status code 200, with default header values.

OK
*/
type LineGetOK struct {
	Payload []*models.TflAPIPresentationEntitiesLine
}

// IsSuccess returns true when this line get o k response has a 2xx status code
func (o *LineGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this line get o k response has a 3xx status code
func (o *LineGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this line get o k response has a 4xx status code
func (o *LineGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this line get o k response has a 5xx status code
func (o *LineGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this line get o k response a status code equal to that given
func (o *LineGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the line get o k response
func (o *LineGetOK) Code() int {
	return 200
}

func (o *LineGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/{ids}][%d] lineGetOK %s", 200, payload)
}

func (o *LineGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/{ids}][%d] lineGetOK %s", 200, payload)
}

func (o *LineGetOK) GetPayload() []*models.TflAPIPresentationEntitiesLine {
	return o.Payload
}

func (o *LineGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
