// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// LineDisruptionReader is a Reader for the LineDisruption structure.
type LineDisruptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineDisruptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewLineDisruptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Line/{ids}/Disruption] Line_Disruption", response, response.Code())
	}
}

// NewLineDisruptionOK creates a LineDisruptionOK with default headers values
func NewLineDisruptionOK() *LineDisruptionOK {
	return &LineDisruptionOK{}
}

/*
LineDisruptionOK describes a response with status code 200, with default header values.

OK
*/
type LineDisruptionOK struct {
	Payload []*models.TflAPIPresentationEntitiesDisruption
}

// IsSuccess returns true when this line disruption o k response has a 2xx status code
func (o *LineDisruptionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this line disruption o k response has a 3xx status code
func (o *LineDisruptionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this line disruption o k response has a 4xx status code
func (o *LineDisruptionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this line disruption o k response has a 5xx status code
func (o *LineDisruptionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this line disruption o k response a status code equal to that given
func (o *LineDisruptionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the line disruption o k response
func (o *LineDisruptionOK) Code() int {
	return 200
}

func (o *LineDisruptionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/{ids}/Disruption][%d] lineDisruptionOK %s", 200, payload)
}

func (o *LineDisruptionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/{ids}/Disruption][%d] lineDisruptionOK %s", 200, payload)
}

func (o *LineDisruptionOK) GetPayload() []*models.TflAPIPresentationEntitiesDisruption {
	return o.Payload
}

func (o *LineDisruptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
