// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// LineMetaModesReader is a Reader for the LineMetaModes structure.
type LineMetaModesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineMetaModesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewLineMetaModesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Line/Meta/Modes] Line_MetaModes", response, response.Code())
	}
}

// NewLineMetaModesOK creates a LineMetaModesOK with default headers values
func NewLineMetaModesOK() *LineMetaModesOK {
	return &LineMetaModesOK{}
}

/*
LineMetaModesOK describes a response with status code 200, with default header values.

OK
*/
type LineMetaModesOK struct {
	Payload []*models.TflAPIPresentationEntitiesMode
}

// IsSuccess returns true when this line meta modes o k response has a 2xx status code
func (o *LineMetaModesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this line meta modes o k response has a 3xx status code
func (o *LineMetaModesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this line meta modes o k response has a 4xx status code
func (o *LineMetaModesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this line meta modes o k response has a 5xx status code
func (o *LineMetaModesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this line meta modes o k response a status code equal to that given
func (o *LineMetaModesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the line meta modes o k response
func (o *LineMetaModesOK) Code() int {
	return 200
}

func (o *LineMetaModesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/Meta/Modes][%d] lineMetaModesOK %s", 200, payload)
}

func (o *LineMetaModesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/Meta/Modes][%d] lineMetaModesOK %s", 200, payload)
}

func (o *LineMetaModesOK) GetPayload() []*models.TflAPIPresentationEntitiesMode {
	return o.Payload
}

func (o *LineMetaModesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
