// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// LineRouteSequenceReader is a Reader for the LineRouteSequence structure.
type LineRouteSequenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineRouteSequenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewLineRouteSequenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Line/{id}/Route/Sequence/{direction}] Line_RouteSequence", response, response.Code())
	}
}

// NewLineRouteSequenceOK creates a LineRouteSequenceOK with default headers values
func NewLineRouteSequenceOK() *LineRouteSequenceOK {
	return &LineRouteSequenceOK{}
}

/*
LineRouteSequenceOK describes a response with status code 200, with default header values.

OK
*/
type LineRouteSequenceOK struct {
	Payload *models.TflAPIPresentationEntitiesRouteSequence
}

// IsSuccess returns true when this line route sequence o k response has a 2xx status code
func (o *LineRouteSequenceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this line route sequence o k response has a 3xx status code
func (o *LineRouteSequenceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this line route sequence o k response has a 4xx status code
func (o *LineRouteSequenceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this line route sequence o k response has a 5xx status code
func (o *LineRouteSequenceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this line route sequence o k response a status code equal to that given
func (o *LineRouteSequenceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the line route sequence o k response
func (o *LineRouteSequenceOK) Code() int {
	return 200
}

func (o *LineRouteSequenceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/{id}/Route/Sequence/{direction}][%d] lineRouteSequenceOK %s", 200, payload)
}

func (o *LineRouteSequenceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/{id}/Route/Sequence/{direction}][%d] lineRouteSequenceOK %s", 200, payload)
}

func (o *LineRouteSequenceOK) GetPayload() *models.TflAPIPresentationEntitiesRouteSequence {
	return o.Payload
}

func (o *LineRouteSequenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesRouteSequence)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
