// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"tfltt/tfl/models"
)

// LineArrivalsReader is a Reader for the LineArrivals structure.
type LineArrivalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineArrivalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewLineArrivalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Line/{ids}/Arrivals/{stopPointId}] Line_Arrivals", response, response.Code())
	}
}

// NewLineArrivalsOK creates a LineArrivalsOK with default headers values
func NewLineArrivalsOK() *LineArrivalsOK {
	return &LineArrivalsOK{}
}

/*
LineArrivalsOK describes a response with status code 200, with default header values.

OK
*/
type LineArrivalsOK struct {
	Payload []*models.TflAPIPresentationEntitiesPrediction
}

// IsSuccess returns true when this line arrivals o k response has a 2xx status code
func (o *LineArrivalsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this line arrivals o k response has a 3xx status code
func (o *LineArrivalsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this line arrivals o k response has a 4xx status code
func (o *LineArrivalsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this line arrivals o k response has a 5xx status code
func (o *LineArrivalsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this line arrivals o k response a status code equal to that given
func (o *LineArrivalsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the line arrivals o k response
func (o *LineArrivalsOK) Code() int {
	return 200
}

func (o *LineArrivalsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/{ids}/Arrivals/{stopPointId}][%d] lineArrivalsOK %s", 200, payload)
}

func (o *LineArrivalsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Line/{ids}/Arrivals/{stopPointId}][%d] lineArrivalsOK %s", 200, payload)
}

func (o *LineArrivalsOK) GetPayload() []*models.TflAPIPresentationEntitiesPrediction {
	return o.Payload
}

func (o *LineArrivalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
